mutation deleteProjectedPeriod($deleteIdData: DeleteIDInput!){
    deleteProjectedPeriod(deleteIdData: $deleteIdData){
        createdBy
        createdAt
        modifiedBy
        modifiedAt
        deletedBy
        deletedAt
        id
        date
        companyId
    }
}