import gql from 'graphql-tag'

export default gql`query prenominaPeriods($id: ID, $name: String, $prenominaConfigurationId: ID, $completed: Boolean, $totalVacancies: Float, $prenominaPeriodEmployees: [PrenominaPeriodEmployeeInput!], $offset: Int, $limit: Int){
    prenominaPeriods(id: $id, name: $name, prenominaConfigurationId: $prenominaConfigurationId, completed: $completed, totalVacancies: $totalVacancies, prenominaPeriodEmployees: $prenominaPeriodEmployees, offset: $offset, limit: $limit){
        createdBy
        createdAt
        modifiedBy
        modifiedAt
        deletedBy
        deletedAt
        id
        name
        prenominaConfigurationId
        completed
        totalVacancies {
          clientName
          clientServiceName
          totalVacancies
        }
        prenominaPeriodEmployees{
            createdBy
            createdAt
            modifiedBy
            modifiedAt
            deletedBy
            deletedAt
            id
            employeeId
            prenominaPeriodId
            keycode
            bankAccount
            clientName
            salary
            absences
            saving
            uniforms
            advance
            double
            bonus
            holiday
            infonavit
            fonacot
            loan
            nss
            total
            employee{
                createdBy
                createdAt
                modifiedBy
                modifiedAt
                deletedBy
                deletedAt
                id
                keycode
                bankAccount
                person{
                    name
                    lastName
                    phoneContacts
                    emails
                    comments
                    address{
                        name
                        street
                        exteriorNumber
                        interiorNumber
                        neightborhood
                        city
                        state
                        country
                        postalCode
                    }
                }
                positionId
                hiringDate
                startOperationDate
                clientId
                clientServiceId
                companyId
                address{
                    name
                    street
                    exteriorNumber
                    interiorNumber
                    neightborhood
                    city
                    state
                    country
                    postalCode
                }
                attachedQuotePath
                operations{
                    createdBy
                    createdAt
                    modifiedBy
                    modifiedAt
                    deletedBy
                    deletedAt
                    id
                    date
                    employeeId
                    operation
                    operationConfirm
                    restDay
                    workshift
                    hours
                    operationComments
                    operationConfirmComments
                    operationModifiedBy
                    operationConfirmModifiedBy
                }
                company{
                    createdBy
                    createdAt
                    modifiedBy
                    modifiedAt
                    deletedBy
                    deletedAt
                    id
                    name
                    companyGroupId
                    logoImagePath
                    companyId
                    companyGroup{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        name
                    }
                    companyParent{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        name
                        companyGroupId
                        logoImagePath
                        companyId
                    }
                    users{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        username
                        email
                        firstName
                        lastName
                        roleAccessId
                        companyId
                    }
                    company{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        name
                        companyGroupId
                        logoImagePath
                        companyId
                    }
                    processList{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        name
                        order
                        functionsIds
                        companyId
                    }
                    clients{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        keycode
                        rfc
                        businessName
                        businessReason
                        companyId
                    }
                }
                client{
                    createdBy
                    createdAt
                    modifiedBy
                    modifiedAt
                    deletedBy
                    deletedAt
                    id
                    keycode
                    rfc
                    businessName
                    businessReason
                    legalRepresentativeContact{
                        name
                        lastName
                        phoneContacts
                        emails
                        comments
                    }
                    fiscalAddress{
                        name
                        street
                        exteriorNumber
                        interiorNumber
                        neightborhood
                        city
                        state
                        country
                        postalCode
                    }
                    companyId
                    company{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        name
                        companyGroupId
                        logoImagePath
                        companyId
                    }
                    customer{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        processId
                        commercialValue
                        attemptClosingDate
                        clientId
                        clientServiceId
                        hidden
                        customerName
                        catalogPriority
                        attachedQuotePath
                        comments
                        remindDate
                        emails
                    }
                    clientServices{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        keycode
                        clientId
                        name
                        serviceType
                        scheduleHours
                        serviceCost
                        elementCost
                        patrolCost
                        quadBikeCost
                        bossShiftCost
                        qrCost
                        costHolyDays
                        addressExecution
                        totalElementsDay
                        totalElementsNight
                        totalPatrol
                        totalQuadBike
                        startDate
                        creditDays
                        paymentDays
                        folioCounterReceipt
                        billing
                        branchBank
                        lastFourDigits
                        paymentMethod
                        usageCfdi
                        paymentForm
                        description
                    }
                    positions{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        name
                        clientId
                        salary
                        requiredDocumentsPaths
                    }
                }
                clientService{
                    createdBy
                    createdAt
                    modifiedBy
                    modifiedAt
                    deletedBy
                    deletedAt
                    id
                    keycode
                    clientId
                    name
                    serviceType
                    scheduleHours
                    serviceCost
                    elementCost
                    patrolCost
                    quadBikeCost
                    bossShiftCost
                    qrCost
                    costHolyDays
                    addressExecution
                    totalElementsDay
                    totalElementsNight
                    totalPatrol
                    totalQuadBike
                    startDate
                    emergencyContact{
                        name
                        lastName
                        phoneContacts
                        emails
                        comments
                    }
                    paymentContact{
                        name
                        lastName
                        phoneContacts
                        emails
                        comments
                    }
                    creditDays
                    paymentDays
                    folioCounterReceipt
                    billing
                    branchBank
                    lastFourDigits
                    paymentMethod
                    usageCfdi
                    paymentForm
                    description
                    client{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        keycode
                        rfc
                        businessName
                        businessReason
                        companyId
                    }
                }
                position{
                    createdBy
                    createdAt
                    modifiedBy
                    modifiedAt
                    deletedBy
                    deletedAt
                    id
                    name
                    clientId
                    salary
                    requiredDocumentsPaths
                    client{
                        createdBy
                        createdAt
                        modifiedBy
                        modifiedAt
                        deletedBy
                        deletedAt
                        id
                        keycode
                        rfc
                        businessName
                        businessReason
                        companyId
                    }
                }
            }
            prenominaPeriodEmployeeDays{
                createdBy
                createdAt
                modifiedBy
                modifiedAt
                deletedBy
                deletedAt
                id
                prenominaPeriodEmployeeId
                date
                operationText
                operationAbbreviation
            }
        }
    }
}`
