import gql from 'graphql-tag'

export default gql`query prenominaPeriodEmployee($id: ID, $employeeId: ID, $prenominaPeriodId: ID, $keycode: String, $bankAccount: String, $clientName: String, $salary: Float, $absences: Float, $saving: Float, $uniforms: Float, $advance: Float, $double: Float, $bonus: Float, $holiday: Float, $infonavit: Float, $fonacot: Float, $loan: Float, $nss: Float, $total: Float, $employee: EmployeeInput, $prenominaPeriodEmployeeDays: [PrenominaPeriodEmployeeDayInput!], $offset: Int, $limit: Int){
    prenominaPeriodEmployee(id: $id, employeeId: $employeeId, prenominaPeriodId: $prenominaPeriodId, keycode: $keycode, bankAccount: $bankAccount, clientName: $clientName, salary: $salary, absences: $absences, saving: $saving, uniforms: $uniforms, advance: $advance, double: $double, bonus: $bonus, holiday: $holiday, infonavit: $infonavit, fonacot: $fonacot, loan: $loan, nss: $nss, total: $total, employee: $employee, prenominaPeriodEmployeeDays: $prenominaPeriodEmployeeDays, offset: $offset, limit: $limit){
        createdBy
        createdAt
        modifiedBy
        modifiedAt
        deletedBy
        deletedAt
        id
        employeeId
        prenominaPeriodId
        keycode
        bankAccount
        clientName
        salary
        absences
        saving
        uniforms
        advance
        double
        bonus
        holiday
        infonavit
        fonacot
        loan
        nss
        total
        employee{
            createdBy
            createdAt
            modifiedBy
            modifiedAt
            deletedBy
            deletedAt
            id
            keycode
            bankAccount
            person{
                name
                lastName
                phoneContacts
                emails
                comments
                address{
                    name
                    street
                    exteriorNumber
                    interiorNumber
                    neightborhood
                    city
                    state
                    country
                    postalCode
                }
            }
            positionId
            hiringDate
            startOperationDate
            clientId
            clientServiceId
            companyId
            address{
                name
                street
                exteriorNumber
                interiorNumber
                neightborhood
                city
                state
                country
                postalCode
            }
            attachedQuotePath
        }
    }
}`
