import { CREATE_CLIENT, DELETE_CLIENT, UPDATE_CLIENT, GET_CLIENT, GET_CLIENTS } from './clients'

import {
  CREATE_SYSTEM_ALERT,
  DELETE_SYSTEM_ALERT,
  UPDATE_SYSTEM_ALERT,
  GET_SYSTEM_ALERT,
  GET_SYSTEM_ALERTS,
  GET_SYSTEM_ALERTS_BY_SESSION
} from './system-alerts'

import {
  GET_IMAGE,
  GET_IMAGES,
  CREATE_IMAGE,
  UPDATE_IMAGE,
  DELETE_IMAGE
} from './images'

export const ADMIN_OPERATIONS = {
  CREATE_CLIENT,
  DELETE_CLIENT,
  UPDATE_CLIENT,
  GET_CLIENT,
  GET_CLIENTS,

  CREATE_SYSTEM_ALERT,
  DELETE_SYSTEM_ALERT,
  UPDATE_SYSTEM_ALERT,
  GET_SYSTEM_ALERT,
  GET_SYSTEM_ALERTS,
  GET_SYSTEM_ALERTS_BY_SESSION,

  GET_IMAGE,
  GET_IMAGES,
  CREATE_IMAGE,
  UPDATE_IMAGE,
  DELETE_IMAGE
}
